import { supabase } from "../supabaseClient"
import { useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import TaskList from "../components/TaskList";
import "starability/starability-css/starability-basic.css"
import StatsBar from "../components/StatsBar";

export default function Dashboard() {

    const navigate = useNavigate()

    const [username, setUsername] = useState("")
    const [taskName, setTaskName] = useState("")
    const [date, setDate] = useState("")
    const [checkinTime, setCheckinTime] = useState("")
    const [message, setMessage] = useState("")
    const [tasks, setTasks] = useState([])
    const [inviteLink, setInviteLink] = useState("")
    const [partnerEmail, setPartnerEmail] = useState("")
    const [inviteLinkPrompt, setInviteLinkPrompt] = useState("")
    const [unregisteredUserMessage, setUnregisteredUserMessage] = useState("")
    const [taskMessages, setTaskMessages] = useState({})
    const [statsRefreshKey, setStatsRefreshKey] = useState(0)
    const [copied, setCopied] = useState(false)

    const updateTaskName = (e) => {
        setTaskName(e.target.value)
    }

    const updateDate = (e) => {
        setDate(e.target.value)
    }

    const updateCheckinTime = (e) => {
        setCheckinTime(e.target.value)
    }

    const updatePartnerEmail = (e) => {
        setPartnerEmail(e.target.value)
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        const combinedDateTime = `${date}T${checkinTime}:00`
        const { data: { user } } = await supabase.auth.getUser()
        const taskObject = {
            title: taskName,
            due_date: date,
            check_in_time: combinedDateTime,
            user_id: user.id,
            status: "pending"
        }
        const { data, error } = await supabase
            .from('tasks')
            .insert(taskObject)
            // The issue is likely that when the component first renders, tasks is an empty array [] and then a newly added task gets added via setTasks([...tasks, taskObject]) — but taskObject doesn't have an id field because id is generated by Supabase, not by you. So the new task in state has id: undefined, which means key={task.id} is key={undefined} — React complains. After the insert, re-fetch instead of manually updating state, or fetch the inserted row which Supabase can return by adding .select() to your insert
            .select()
        if (error) {
            setMessage("Couldn't update database", error.message)
        } else {
            setMessage("Task added successfully")
            //  add the new task to state so the list updates without re-fetching:
            // .select() at the end tells Supabase to return the inserted row — including the id that was generated. data[0] is that row. Now the new task in state has a real id and the key warning disappears.
            setTasks([...tasks, data[0]])
            setTaskName("")
            setDate("")
            setCheckinTime("")
            setStatsRefreshKey(prev => prev + 1)

        }
    }
    //crypto.randomUUID() which is built into modern browsers and generates a guaranteed unique string:


    const handleCreateInviteLink = async () => {
        const randomInviteLink = `${window.location.origin}/invite/${crypto.randomUUID()}`
        const { data: { user } } = await supabase.auth.getUser()
        const partnerShipObject = {
            doer_id: user.id,
            status: "pending",
            invite_link: randomInviteLink
        }
        const { error } = await supabase
            .from('partnerships')
            .insert(partnerShipObject)
        if (error) {
            console.log("Error creating invite link", error.message)
        } else {
            setInviteLink(randomInviteLink)
            setInviteLinkPrompt("Share the invite link above with your partner")
        }
    }

    const handlePartnerInvite = async () => {
        const randomInviteLink = `${window.location.origin}/invite/${crypto.randomUUID()}`
        // 4 Criterias:
        const { data: { user } } = await supabase.auth.getUser()
        // search for email id through profile table,
        const { data: profilesData, error: profilesError } = await supabase
            .from("profiles")
            .select("id")
            .eq("email", partnerEmail)


        // profileError is either null (no error) or an error object — not an array. So profileError[0] is trying to access index 0 of null, which crashes.
        // Since you removed .single(), profileData is now an array. So:
        // profileError to check if the query failed
        // profileData.length === 0 to check if no matching user was found
        if (profilesError || profilesData.length === 0) {
            setUnregisteredUserMessage("No user found with that email, generate and share the invite link instead.")
            return
        } else if (profilesData[0].id === user.id) {
            setUnregisteredUserMessage("You cannot invite yourself as a partner.")
            return
        }

        const { data: partnershipData } = await supabase
            .from("partnerships")
            .select("id")
            .eq("doer_id", user.id)
            .eq("partner_id", profilesData[0].id)
        // if(invite already exist for the same doer-partner combo){
        // query table and check,
        // show message informing,
        // can only send another invite in 7 days 
        // or generate a random inv link}

        if (partnershipData[0]) {
            setUnregisteredUserMessage("You have already invited this person, please generate a random link below if you want to invite them again")
            return
        } else {
            // update the partnership table with Link, status and both ids
            const inviteLinkObject = {
                doer_id: user.id,
                status: "pending",
                invite_link: randomInviteLink,
                partner_id: profilesData[0].id
            }
            const { error } = await supabase
                .from("partnerships")
                .insert(inviteLinkObject)
            setUnregisteredUserMessage("")
            if (error) {
                console.log("Error creating invite link", error.message)
            } else {
                setInviteLink(randomInviteLink)
            }
            // send email invite, create and store random inv link, do it later through an email service
        }
        // one user = max 2 people invite at one time
    }



    const handleLogout = async () => {
        const { error } = await supabase.auth.signOut()
        if (error) {
            console.log(error.message);
        } else {
            navigate("/login")
        }
    }

    useEffect(() => {

        // fetchData() should be called inside the useEFffect() function
        const fetchData = async () => {
            const { data: { user } } = await supabase.auth.getUser()
            const { data: tasksData, error } = await supabase
                .from("tasks")
                .select("*")
                .eq("user_id", user.id)
            if (error) {
                console.log(error.message)
                return
            }

            const { data: profilesData, error: profilesError } = await supabase
                .from("profiles")
                .select("username")
                .eq("id", user.id)
                .single()

            if (profilesError) {
                console.log(error.message)
                return
            }
            setUsername(profilesData.username)

            const selfTaskWithUrls = await Promise.all(tasksData.map(async (task) => {
                if (!task.evidence_path) return task  // no evidence yet, skip
                const { data } = await supabase.storage
                    .from('evidence')
                    .createSignedUrl(task.evidence_path, 36006)
                return { ...task, signedUrl: data?.signedUrl || null }
            }))
            setTasks(selfTaskWithUrls)
            setStatsRefreshKey(prev => prev + 1)

            if (!message) return

            const timer = setTimeout(() => {
                setMessage("")
            }, 3000)

            return () => clearTimeout(timer)
        }
        // if fetchData is not called inside the useEffect(), this will cause an infinite loop — every time setTasks() updates state, the component re-renders, which calls fetchData() again, which calls setTasks() again, forever.
        fetchData()
    }, [message])

    const handleCheckIn = async (task, selectedFiles) => {
        const actualCheckInTime = new Date().toISOString()
        const { data: { user } } = await supabase.auth.getUser()
        const filePath = `${user.id}/${task.task_key}/${actualCheckInTime}.png`
        let signedUrl = null
        if (selectedFiles[task.task_key]) {
            const { error: uploadError } = await supabase.storage
                .from('evidence')
                .upload(filePath, selectedFiles[task.task_key])

            if (uploadError) {
                setTaskMessages(prev => ({ ...prev, [task.task_key]: "Upload Failed!!" }))
                return
            } else {
                setTaskMessages(prev => ({ ...prev, [task.task_key]: "Uploaded Successfully" }))
            }

            const { data: urlData } = await supabase.storage
                .from("evidence")
                .createSignedUrl(filePath, 3600)

            signedUrl = urlData.signedUrl
        }

        const { data: tasksData, error: tasksError } = await supabase
            .from("tasks")
            .update({
                status: "checkedIn",
                actual_check_in_time: actualCheckInTime,
                ...(signedUrl && { evidence_path: filePath })
            })
            .eq("task_key", task.task_key)
            .select()

        if (tasksError) {
            setTaskMessages(prev => ({
                ...prev,
                [task.task_key]: "Unable to update check in status, please try again"
            }))
            console.log(tasksError.message)
            return
        }

        setTasks(tasks.map(t =>
            t.task_key === task.task_key
                ? { ...t, status: "checkedIn", ...(signedUrl && { signedUrl }) }
                : t
        ))
        if (new Date(actualCheckInTime) > new Date(tasksData[0].check_in_time)) {
            setTaskMessages(prev => ({
                ...prev,
                [task.task_key]: "You checked in late"
            }))
        } else {
            setTaskMessages(prev => ({
                ...prev,
                [task.task_key]: "You completed your task before time"
            }))
        }
        setStatsRefreshKey(prev => prev + 1)
        // The difference is the timezone suffix — +00:00 vs Z. Both mean UTC but as strings they're different, which could throw off the comparison in edge cases.
        // new Date() converts both to proper Date objects first, eliminating any formatting differences before comparing
    }

    return (
        <>
            <section className="mx-auto max-w-6xl px-4 py-8 md:px-12 md:py-12">
                {/* Header */}
                <div className="mb-12">
                    <h1 className="font-serif text-3xl font-extrabold tracking-wide md:text-5xl">
                        Welcome back,
                        <span className="block text-lime-500 md:ml-3 md:inline">
                            {username}
                        </span>
                    </h1>

                    <p className="mt-4 max-w-2xl font-mono text-lg text-zinc-600">
                        Stay accountable, complete your tasks, and keep your streak alive.
                    </p>
                </div>
                <div className="flex justify-center">
                    <button
                        onClick={() => navigate('/partner-dashboard')}
                        className="
                        w-full max-w-xs
                        rounded-2xl
                        bg-amber-500
                        px-8
                        py-4
                        mb-8
                        font-extrabold
                        uppercase
                        text-white
                        shadow-[0_4px_0_rgb(74,124,0)]
                        cursor-pointer
                        transition-all
                        hover:bg-amber-400">Partners-Dashboard</button>
                </div>

                <div>
                    <StatsBar refreshKey={statsRefreshKey} />

                    {/* Create new Task */}
                    <div className="rounded-3xl border bg-white p-8 shadow-sm mb-8">
                        <h2 className="mb-6 text-3xl font-extrabold text-lime-500">
                            Create Task
                        </h2>

                        <form
                            onSubmit={handleSubmit}
                            className="space-y-6"
                        >
                            <input
                                type="text"
                                placeholder="Enter Task Name"
                                value={taskName}
                                onChange={updateTaskName}
                                id="task-name"
                                className="w-full rounded-2xl border border-zinc-500 px-5 py-4"
                            />

                            <div className="grid gap-4 md:grid-cols-2">
                                <input
                                    type="date"
                                    value={date}
                                    onChange={updateDate}
                                    id="date"
                                    className="rounded-2xl border border-zinc-500 px-5 py-4"
                                />

                                <input
                                    type="time"
                                    value={checkinTime}
                                    onChange={updateCheckinTime}
                                    id="checkin-time"
                                    className="rounded-2xl border border-zinc-500 px-5 py-4"
                                />
                            </div>
                            <button
                                type="submit"
                                className="
                                w-80
                                rounded-2xl
                                bg-lime-500
                                px-8
                                py-4
                                font-extrabold
                                uppercase
                                text-white
                                shadow-[0_4px_0_rgb(74,124,0)]
                                cursor-pointer
                                transition-all
                                hover:bg-lime-400"
                            >
                                Create Task
                            </button>
                        </form>
                    </div>

                </div>
                {/* <TaskList {...tasks} /> is wrong
            ...tasks spreads the array as individual props, not as a single tasks prop. TaskList expects to receive tasks as a named prop */}
                <div className="mx-auto max-w-6xl">
                    <TaskList
                        tasks={tasks}
                        onCheckIn={handleCheckIn}
                        taskMessages={taskMessages}
                    />
                    {message && (
                        <div
                            className="
                            fixed
                            bottom-8
                            right-8
                            z-50

                            rounded-2xl
                            border
                            border-lime-200
                            bg-lime-50

                            px-6
                            py-4

                            shadow-lg
                        "
                        >
                            <div className="flex items-center gap-3">
                                <span
                                    className="
                                    flex
                                    h-8
                                    w-8
                                    items-center
                                    justify-center
                                    rounded-full
                                    bg-lime-500
                                    text-white
                                    font-bold
                                "
                                >
                                    ✓
                                </span>

                                <span className="font-semibold text-lime-700">
                                    {message}
                                </span>
                            </div>
                        </div>
                    )}
                </div>

                {/* Invite Partner through an Invite link */}
                <div className="rounded-3xl border border-zinc-300 bg-white p-8 shadow-sm mb-8 ">
                    <h2 className="mb-6 text-3xl font-extrabold text-sky-500">
                        Invite your Partner
                    </h2>

                    <div className="space-y-4">
                        <input
                            type="email"
                            value={partnerEmail}
                            onChange={updatePartnerEmail}
                            id="partner-email"
                            placeholder="Partner email"
                            className="w-80 border-2 rounded-2xl border-zinc-300 px-5 py-3 text-lg font-medium outline-none transition-all focus:border-sky-400 focus:ring-4 focus:ring-sky-100"
                        />

                        <div className="flex gap-4">
                            <button onClick={handlePartnerInvite} className="rounded-2xl
                                        bg-sky-500
                                        px-6
                                        py-3
                                        mt-4

                                        font-bold
                                        text-white

                                        shadow-[0_3px_0_rgb(3,105,161)]

                                        transition-all

                                        hover:bg-sky-400
                                        active:translate-y-0.5
                                        active:shadow-none

                                        cursor-pointer">
                                Send Invite
                            </button>

                            <button onClick={handleCreateInviteLink} className="rounded-2xl
                                        bg-zinc-200
                                        px-6
                                        py-3
                                        mt-4

                                        font-bold
                                        text-black

                                        shadow-[0_3px_0_rgb(212,212,212)]

                                        transition-all

                                        hover:bg-zinc-300
                                        active:translate-y-0.5
                                        active:shadow-none

                                        cursor-pointer">
                                Create Invite Link
                            </button>

                        </div>
                        <p className="text-sm text-zinc-600">{unregisteredUserMessage}</p>
                    </div>
                    {inviteLink && (
                        <div
                            className="
                            mt-6
                            rounded-2xl
                            border
                            border-lime-200
                            bg-lime-50
                            p-6
                        "
                        >
                            <div className="mb-4 flex items-center gap-3">
                                <div
                                    className="
                                    flex
                                    h-10
                                    w-10
                                    items-center
                                    justify-center
                                    rounded-full
                                    bg-lime-500
                                    text-xl
                                    font-bold
                                    text-white
                                "
                                >
                                    ✓
                                </div>

                                <div>
                                    <h3 className="font-bold text-lime-700">
                                        Invite Link Created
                                    </h3>

                                    <p className="text-sm text-zinc-600">
                                        Share this link with your partner
                                    </p>
                                </div>
                            </div>

                            <div
                                className="
                                flex
                                items-center
                                justify-between
                                gap-4

                                rounded-xl
                                border
                                bg-white

                                px-4
                                py-3
                            "
                            >
                                <span
                                    className="
                                    flex-1
                                    truncate
                                    text-sm
                                    text-zinc-600
                                "
                                >
                                    {inviteLink}
                                </span>

                                <button
                                    onClick={() => {
                                        navigator.clipboard.writeText(inviteLink)
                                        setCopied(true)

                                        setTimeout(() => {
                                            setCopied(false)
                                        }, 2000)
                                    }}
                                    className="
                                    rounded-xl
                                    bg-sky-500
                                    px-4
                                    py-2
                                    text-sm
                                    font-bold
                                    text-white
                                    shadow-[0_3px_0_rgb(3,105,161)]
                                    transition-all
                                    hover:bg-sky-400
                                    active:translate-y-0.5
                                    active:shadow-none
                                    cursor-pointer
                                "
                                >
                                    {copied ? "Copied!" : "Copy Link"}
                                </button>
                            </div>

                            <p className="mt-4 text-sm text-zinc-500">
                                {inviteLinkPrompt}
                            </p>
                        </div>
                    )}
                </div>
                <div className="flex justify-center">
                    <button onClick={handleLogout}
                        className="
                        w-80
                        rounded-2xl
                        bg-rose-700
                        px-8
                        py-4
                        mb-8
                        font-extrabold
                        uppercase
                        text-white
                        shadow-[0_4px_0_rgb(74,124,0)]
                        cursor-pointer
                        transition-all
                        hover:bg-rose-500">Logout</button>
                </div>

            </section>

        </>
    )
}